---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - path: rhtap-infra-secrets-patch.yaml
    target:
      name: rhtap-infra-secrets
      kind: ExternalSecret
      group: external-secrets.io
      version: v1beta1
