apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- toolchain-member-operator.yaml
- sandbox-sre-member.yaml
- ../../user-management/staging/generated-manifests/member

