apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/redhat-appstudio/release-service/config/default?ref=3b6255c66b5e6f69385feca861ce5aadfe6a6e2b

images:
  - name: quay.io/redhat-appstudio/release-service
    newName: quay.io/redhat-appstudio/release-service
    newTag: 3b6255c66b5e6f69385feca861ce5aadfe6a6e2b

namespace: release-service
