apiVersion: toolchain.dev.openshift.com/v1alpha1
kind: SpaceProvisionerConfig
metadata:
  name: member-stone-stage-p01.apys.p3.openshiftapps.com
  namespace: toolchain-host-operator
spec:
  toolchainCluster: member-stone-stage-p01.apys.p3.openshiftapps.com
  enabled: true
  capacityThresholds:
    maxNumberOfSpaces: 1500
    maxMemoryUtilizationPercent: 90
  placementRoles:
  - cluster-role.toolchain.dev.openshift.com/tenant