clusters:
  host:
    api: https://api.stone-stg-host.qc0p.p1.openshiftapps.com:6443
  members:
  - api: https://api.stone-stg-m01.7ayg.p1.openshiftapps.com:6443
    name: member-1
  - api: https://api.stone-stg-rh01.l2vh.p1.openshiftapps.com:6443
    name: member-rh-1

serviceAccounts:
## service accounts to be used by humans via `sandbox-cli`
- name: dperaza4dustbit
  host:
    roleBindings:
    - namespace: toolchain-host-operator
      roles:
      - install-operator
      - restart-deployment
      - approve-user
      - view-secrets
      - deactivate-user
      - ban-user
      - promote-user
      - retarget-user
      - gdpr-delete
      clusterRoles:
      - view
      - edit

  member:
    roleBindings:
    - namespace: toolchain-member-operator
      roles:
      - install-operator
      - restart-deployment
      - view-secrets
      clusterRoles:
      - view
      - edit

- name: alkazako
  host:
    roleBindings:
    - namespace: toolchain-host-operator
      roles:
      - install-operator
      - restart-deployment
      - approve-user
      - view-secrets
      - deactivate-user
      - ban-user
      - promote-user
      - retarget-user
      - gdpr-delete
      clusterRoles:
      - view
      - edit

  member:
    roleBindings:
    - namespace: toolchain-member-operator
      roles:
      - install-operator
      - restart-deployment
      - view-secrets
      clusterRoles:
      - view
      - edit

- name: mjobanek
  host:
    roleBindings:
    - namespace: toolchain-host-operator
      roles:
      - approve-user
      - view-secrets
      - deactivate-user
      - ban-user
      - promote-user
      - retarget-user
      - gdpr-delete
      - install-operator
      - restart-deployment
      clusterRoles:
      - view
      - edit

  member:
    roleBindings:
    - namespace: toolchain-member-operator
      roles:
      - install-operator
      - restart-deployment
      - view-secrets
      clusterRoles:
      - view
      - edit

- name: fmuntean
  host:
    roleBindings:
    - namespace: toolchain-host-operator
      roles:
      - approve-user
      - view-secrets
      - deactivate-user
      - ban-user
      - promote-user
      - retarget-user
      - gdpr-delete
      - restart-deployment
      clusterRoles:
      - edit
      - view
  member:
    roleBindings:
    - namespace: toolchain-member-operator
      roles:
      - restart-deployment
      - view-secrets
      clusterRoles:
      - edit
      - view

- name: bkundu
  host:
    roleBindings:
    - namespace: toolchain-host-operator
      roles:
      - approve-user
      - deactivate-user
      - promote-user
      - retarget-user
      - gdpr-delete
      clusterRoles:
      - view
  member:
    roleBindings:
    - namespace: toolchain-member-operator
      roles:
      - restart-deployment
      clusterRoles:
      - view

- name: rorai
  host:
    roleBindings:
    - namespace: toolchain-host-operator
      roles:
      - approve-user
      - deactivate-user
      - gdpr-delete
      - retarget-user
      clusterRoles:
      - view
  member:
    roleBindings:
    - namespace: toolchain-member-operator
      clusterRoles:
      - view

- name: pdave
  host:
    roleBindings:
    - namespace: toolchain-host-operator
      roles:
      - approve-user
      - deactivate-user
      - gdpr-delete
      - retarget-user
      - promote-user
      clusterRoles:
      - view
  member:
    roleBindings:
    - namespace: toolchain-member-operator
      clusterRoles:
      - view

- name: bsutter
  host:
    roleBindings:
    - namespace: toolchain-host-operator
      roles:
      - approve-user
      - deactivate-user
      - gdpr-delete
      - retarget-user
      - promote-user
      clusterRoles:
      - view
  member:
    roleBindings:
    - namespace: toolchain-member-operator
      clusterRoles:
      - view

- name: bcook
  host:
    roleBindings:
    - namespace: toolchain-host-operator
      roles:
      - approve-user
      - deactivate-user
      - gdpr-delete
      - retarget-user
      - promote-user
      clusterRoles:
      - view
  member:
    roleBindings:
    - namespace: toolchain-member-operator
      clusterRoles:
      - view

- name: gbenhaim
  host:
    roleBindings:
    - namespace: toolchain-host-operator
      roles:
      - approve-user
      - retarget-user
      clusterRoles:
      - view
  member:
    roleBindings:
    - namespace: toolchain-member-operator
      clusterRoles:
      - view

- name: dfodor
  host:
    roleBindings:
    - namespace: toolchain-host-operator
      roles:
      - approve-user
      - retarget-user
      clusterRoles:
      - view
  member:
    roleBindings:
    - namespace: toolchain-member-operator
      clusterRoles:
      - view

- name: ergonzal
  host:
    roleBindings:
    - namespace: toolchain-host-operator
      roles:
      - approve-user
      - retarget-user
      clusterRoles:
      - view
  member:
    roleBindings:
    - namespace: toolchain-member-operator
      clusterRoles:
      - view

- name: jhutar
  host:
    roleBindings:
    - namespace: toolchain-host-operator
      roles:
      - approve-user
      - gdpr-delete
      clusterRoles:
      - view
  member:
    roleBindings:
    - namespace: toolchain-member-operator
      clusterRoles:
      - view

- name: saviv
  host:
    roleBindings:
    - namespace: toolchain-host-operator
      roles:
      - approve-user
      - retarget-user
      clusterRoles:
      - view
  member:
    roleBindings:
    - namespace: toolchain-member-operator
      clusterRoles:
      - view

- name: ralphbean
  host:
    roleBindings:
    - namespace: toolchain-host-operator
      roles:
      - approve-user
      - retarget-user
      clusterRoles:
      - view
  member:
    roleBindings:
    - namespace: toolchain-member-operator
      clusterRoles:
      - view
